xapi-project/vhd-tool

src/get_vhd_vsize.ml

Fix bad exit code

---

.travis.yml

Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>

Disable opam lint in CI build

---

src/impl.ml

CA-236851: Experimental: Aggresively close VHDs after reading the BAT

---

Makefile
configure.ml

* Fix syntax of conditionals in Makefile
* Don't try to make sparse_dd output groff help, as it can't

Fix issues with Makefile & configure.ml

---

cli/get_vhd_vsize.ml
cli/sparse_dd.ml
src/impl.ml
src/jbuild
vhd-tool.opam

This is part of the `opam/next` patches.
Signed-off-by: Yarsin He <yarsin.he@citrix.com>
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>

[opam/next] Updates to make xs-opam build on next

---

src/impl.ml

Without O_DIRECT we weren't getting IO errors propagated from the
sendfile(2) call (not even on close). This was causing us not to notice
when copying VDIs to full thinly-provisioned SRs.

CA-280242: Open destination VDI O_DIRECT (as well as source).

---

src/channels.ml

Catch EAGAIN from sendfile and retry - this has fixed an intermittent issue in our stress test where VDI export failed randomly with an EAGAIN Unix exception.
All the examples of using sendfile I've found do some kind of retry when getting the EAGAIN error.

Merge of qemu-datapath into REQ477/master branch

---

src/channels.ml

This has fixed an intermittent issue in our stress test where VDI export
failed randomly with an EAGAIN Unix exception.
All the examples of using sendfile I've found do some kind of retry when
getting the EAGAIN error.

[Merge qemu-datapath/ Catch EAGAIN from sendfile and retry

---

.travis.yml
Makefile
cli/sparse_dd.ml
scripts/get_nbd_extents.py
scripts/python_nbd_client.py
src/image.ml
src/image.mli
src/impl.ml
src/jbuild
src/nbd_input.ml
test/dummy_extent_reader.py
test/jbuild
test/suite.ml
vhd-tool.opam

Followup from https://github.com/xapi-project/vhd-tool/pull/56
Fix Travis build, also noticed we don't have ticket numbers on commits, will edit the commit titles.

CA-287921, CP-28020: Copy only allocated & non-zero extents in case of NBD device

---

src/impl.ml

Signed-off-by: Yang Qian <yang.qian@citrix.com>

CA-289145: close socket if error occurs when using lwt connect

---

src/channels.ml
src/impl.ml

Vhd tool fdatasync

---

src/channels.ml

fdatasync will return EINVAL on special files such as pipes, and sockets.
We only want fdatasync if we are writing to a file or block device.

CA-290891: do not call fdatasync on pipes/sockets

---

Makefile
cli/sparse_dd.ml
scripts/get_nbd_extents.py
scripts/python_nbd_client.py
src/impl.ml
src/nbd_input.ml
test/dummy_extent_reader.py
test/jbuild
test/stress.ml

CA-290243: avoid high memory usage during copying from NBD device

---

scripts/get_nbd_extents.py

GFS2  vdi functional tests passed in jobs 2156084, 2156082

[477 merge] CA-290450

---

vhd-tool.opam

Update opam files for Opam 2

---

.travis.yml
Makefile
cli/main.ml
cli/sparse_dd.ml

* Reformat main.ml and sparse_dd.ml. 
* Makefile: option -j is not required
* Makefile: use profile dev for build target
* Makefile: don't require linting for test target

CP-29432 cleanup Makefile, reformat some code

---

src/sendfile64_stubs.c

This is Mark's PR, I've created the 4.19 branch for him from master.

CA-298726: on EINVAL disable O_DIRECT and retry

---

src/channels.ml

Looks like the fix for CA-295097 was not enough.
By reading source code of Lwt I noticed that ch.blocking is a `lazy`
value, and it is only forced by `wrap_syscall` (implicitly called by the other Lwt_unix IO functions).
Do the same for our direct copy/sendfile wrapper, call `wrap_syscall` to
ensure blocking mode is updated if needed.
This still needs testing, which we'll get to later today, opened PR to see if you have some thoughts on this.
/cc @TimSmithCtx

[WiP] CA-309302: ensure we do not get EAGAIN from _sendfile

---

src/impl.ml

Signed-off-by: BenjiReis <benjamin.reis@vates.fr>

Handle IPv6

---

.ocamlformat
Makefile
cli/dune
cli/get_vhd_vsize.ml
cli/main.ml
cli/sparse_dd.ml
dune-project
src/channels.ml
src/chunked.ml
src/cohttp_unbuffered_io.ml
src/common.ml
src/dune
src/iO.ml
src/image.ml
src/image.mli
src/impl.ml
src/input.ml
src/nbd_input.ml
src/streamCommon.ml
src/xenstore.ml
test/dune
test/stress.ml
vhd-tool.opam

Depends on merging https://github.com/xapi-project/nbd/pull/158

CP-34942: update to nbd-unix
