xapi-project/vhd-tool

src/channels.ml
src/impl.ml
src/main.ml
src/sparse_dd.ml
src/streamCommon.ml

To enable TLSv1.2 capability for vhd-tool/sparse_dd,
This changes add 3 new options to CLI parameters,
ssl_legacy: boolean, allow all protocol versions instead of default TLSv1.2
good_ciphersuites: string, SSL good cipher suites for TLS protocols
legacy_ciphersuites: optional string, SSL legacy cipher suites for TLS protocols
Signed-off-by: Phus Lu <phus.lu@citrix.com>

CA-208537: vdi-copy between local SRs proposes unwanted ciphers

---

src/impl.ml

This offset was missed when moving the code to the new sparse dd
library.

Fix: multiply write offset by 512 (sector size)

---

_oasis
_tags
src/impl.ml
src/input.ml

_This PR gets those [ppx changes](https://github.com/xapi-project/vhd-tool/tree/ppx-ely), which can be ported to trunk, into `master`. I could not port the `cstruct` changes into master, because it seems that the `cstruct` `1.4.0` version that we use there only has a camlp4 syntax extension._ 
We are moving away from camlp4 to ppx.
I did not update the files generated by OASIS, because this is done by
the Makefile anyway.

CP-20761 Remove use of camlp4 lwt syntax extension

---

_oasis
_tags
src/chunked.ml
src/impl.ml

* Use the newer ppx version of the cstruct library
* Update to PPX-based NBD library
The other part of the `ppx-ely` branch was ported to `master` in this PR: https://github.com/xapi-project/vhd-tool/pull/35

CP-20761: Rebase ppx-ely branch on trunk

---

_oasis
_tags
src/chunked.ml
src/impl.ml

98c516d 2017-02-22 (HEAD -> ppx_trunk, github-xapi/ppx_trunk) Merge pull request #36 from gaborigloi/ppx_trunk [GitHub]
07ae369 2017-02-02 Fix: multiply write offset by 512 (sector size) [Gabor Igloi]
d307f01 2017-01-25 Update to PPX-based NBD library [Gabor Igloi]
2f2a1d8 2017-01-26 Fix oasis for PPX world [Gabor Igloi]
de25d4e 2017-02-20 (github-xapi/master) Merge pull request #35 from gaborigloi/master_ppx [GitHub]

 Merge ppx_trunk into master for OCaml 4.02.3 and PPX

---

src/impl.ml

We read/update/write the last sectors. Requires that the file
being written to (a block device normally) is at least as large
as the rounded up number of sectors being uploaded.

CA-229038: Allow upload of data that is not an integer number of sectors

---

myocamlbuild.ml

Removed file with the command
oasis setup-clean -replace-sections -remove
This command removes all files generated by OASIS that do not have any
customizations.
This leftover file is not needed, because we auto-generate the OASIS
build files in the Makefile by running "oasis setup".

Remove generated myocamlbuild.ml

---

configure.ml

The closing "]" was missing after the previous commit.

configure.ml: fix generated install file

---

src/impl.ml

We broke the clients of the nbd library when we introduced TLS. This is
a temporary change to fix the build. The new interface of the NBD
library still has to be finalized and polished.

[CBT merge] Temporarily add missing is_tls field to nbd channel record

---

src/jbuild

This depends on https://github.com/xapi-project/netdev/pull/10

CP-24605: Renamed library after porting to jbuilder.

---

src/impl.ml

Without O_DIRECT we weren't getting IO errors propagated from the
sendfile(2) call (not even on close). This was causing us not to notice
when copying VDIs to full thinly-provisioned SRs.
Note that the O_DIRECT open is part of the Vhd_format library and
is controlled by the 'use_unbuffered' global variable of
Vhd_format_lwt.File. See xapi-project/ocaml-vhd for the details.
This was backported from db45f99 by Christian Lindig

CA-280242: Open destination VDI O_DIRECT (as well as source).

---

cli/sparse_dd.ml
src/image.ml

`let (|>) a b = b a` has been a standard part of the language since OCaml 4.01. We can therefore remove these lines from our code.
Signed-off-by: Akanksha Mathur <akanksha.mathur@citrix.com>

Remove redundant definition of (|>) pipe

---

Makefile
test/jbuild
test/stress.ml

- Use @edvintorok's fixes to ensure the python file is always found, no
matter how we run the tests.
- Make sure this stress test does not run as part of the unit test
suite, because it's currently very slow and needs 16GB memory.
It can be run with "make stresstest".

Fix stress test

---

cli/sparse_dd.ml
src/channels.ml
src/cohttp_unbuffered_io.ml
src/common.ml
src/impl.ml

This also adds a fix for a non-exhaustive pattern matching when using NBD. I cannot run the stresstest on my machine because I don't have enough ram

Make safe-string compliant

---

src/channels.ml
src/impl.ml

This is a backport from the master branch to branch 0.11-lcm:
* 2a51dc4 2018-05-25 CA-289459: use fdatasync periodically rather than writing O_DIR.. ..ian Lindig
* 96479f6 2018-05-25 Revert "CA-280242: Open destination VDI O_DIRECT (as well as so.. ..ian Lindig
CA-289459: use fdatasync periodically rather than writing O_DIRECT
This allows tapdisk to coalesce requests which ends up being way
more efficient. We call fdatasync after every 4 megs of data
written.
Signed-off-by: Edwin Török <edvin.torok@citrix.com>

Backport: CA-289459: use fdatasync periodically rather than writing O_DIRECT

---

scripts/get_nbd_extents.py

In my previous fix I forgot to update the limits for the requests we
send to the NBD server - now we no longer want to read the block
descriptors up to the end of the disk.

CA-290450: request block descriptors only for the requested area

---

src/channels.ml

We have customers whose data can't be copied in only 20 tries ( https://bugs.xenserver.org/browse/XSO-873 )
Moreover I see no better response to this error code than trying again, I would suggest removing the limit altogether (if it doesn't work eventually the OS will come with a new error like a closed socket or timeout of some sort).
You might want to slightly randomize the sleep duration and maybe increase it over time.

Wait for FD availability instead of time

---

cli/get_vhd_vsize.ml
cli/main.ml
src/impl.ml

I order to locate the footer in a VHD file or stream, the total length
of that file or stream must be known. This commit passes it when it is
known. This depends on a corresponding change in the ocaml-vhd library.
* https://github.com/mirage/ocaml-vhd/pull/58

XSI-19 locate VHD footer based on file size

---

src/jbuild

Jbuilder/Dune now supports running PPX expanders by default.

Simplify src/jbuild

---

.gitignore
.travis.yml
scripts/get_nbd_extents.py
scripts/python_nbd_client.py

The protocol has been changed, so that now in the response for
NBD_REPLY_TYPE_BLOCK_STATUS, the last extent can extend beyond the
requested area. The old code would fail with an assertion error in this
case. I've fixed the code to correctly deal with this corner case.

 CP-29300: Update get_nbd_extents.py to match latest NBD protocol 

---

.travis.yml
Makefile
cli/get_vhd_vsize.ml
cli/main.ml
cli/sparse_dd.ml
src/cohttp_unbuffered_io.ml
src/iO.ml
src/impl.ml
src/jbuild
vhd-tool.opam

This moves the build to using Dune and removes warnings that are triggered by its stricter rules. It also updates the Travis setup.

Cleanup: move to Dune, remove warnings, update Travis

---

src/direct_copy_stubs.c

If we got an unexpected EOF on read, we would enter an infinite loop
here.
Signed-off-by: Tim Smith <tim.smith@citrix.com>

CA-309290 Catch EOF on read

---

src/direct_copy_stubs.c

The copy wrapper might be handed non-blocking filedescriptors, which
would cause problems. The caller tries not do do that, but it is worth
being robust against it anyway.
Signed-off-by: Tim Smith <tim.smith@citrix.com>

CA-309302 Handle some less common cases in direct_copy

---

src/dune
vhd-tool.opam

compatibility shims with cstruct 2.* got removed in 3.4.0, bu changing the new modules we're compatible with the lastest version of cstruct

CP-30756: cstruct >= 3.0.0 compatibility

---

cli/dune
src/dune

When I did a full opam upgrade vhd-tool failed to build due to some deprecations and more strict checks.
This should be backwards compatible with current xs-opam 4.07.1 and my future 4.08 branch too.

Small build fixes for upcoming package updates

---

.travis.yml
cli/main.ml
cli/sparse_dd.ml
src/channels.ml
src/impl.ml
src/streamCommon.ml

Remove ability for client to pass parameters to enable legacy ssl, and
hard code any ssl contexts to TLS v1.2
Signed-off-by: lippirk <ben.anson@citrix.com>

CP-32843 drop legacy ssl support

---

scripts/get_nbd_extents.py

Fixes some small bugs I noticed when adding nbd extents capabilities to blktap.
These changes can be added independently to the blktap work.
This has gone through a storage bst 139839 and has also gone through the sparse_dd_coalesce.seq JobID:3064205 
Signed-off-by: ben sims <ben.sims@citrix.com>

CP-35115: If server returns no zeros in its flags, don't wait around
